n=input('digite algo:')
print(type(n))
print('e um numero?', n.isnumeric())
print('e alfabetico?', n.isalpha())
print('foi digitado um alfanumerico?', n.isalnum())
print('todos os caracteres sao digitos?', n.isdigit())
print('os caractres sao decimais?', n.isdecimal())
print('foi digitado apenas espaco?', n.isspace())
print('esta em minusculas?', n.islower())
print('esta em maiuscula?', n.isupper())
print('esta capitalizada?', n.istitle())